### ISSUE TITLE
TypeError in tests for read_newlines and show-newlines (no newline argument)

### ISSUE THREAD

**Issue by kloczek** [jaraco/jaraco.text#10]
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-jaraco-text-3.9.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-jaraco-text-3.9.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/jaraco.text-3.9.0, configfile: pytest.ini
plugins: cov-3.0.0
collected 26 items

jaraco/text/__init__.py ...............F.......                                                                                                                      [ 88%]
jaraco/text/layouts.py ..                                                                                                                                            [ 96%]
jaraco/text/show-newlines.py F                                                                                                                                       [100%]

================================================================================= FAILURES =================================================================================
_______________________________________________________________________ [doctest] text.read_newlines _______________________________________________________________________
604
605     >>> tmp_path = getfixture('tmp_path')
606     >>> filename = tmp_path / 'out.txt'
607     >>> _ = filename.write_text('foo\n', newline='')
UNEXPECTED EXCEPTION: TypeError("write_text() got an unexpected keyword argument 'newline'")
Traceback (most recent call last):
  File "/usr/lib64/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest text.read_newlines[2]>", line 1, in <module>
TypeError: write_text() got an unexpected keyword argument 'newline'
/home/tkloczko/rpmbuild/BUILD/jaraco.text-3.9.0/jaraco/text/__init__.py:607: UnexpectedException
_______________________________________________________________ [doctest] text.show-newlines.report_newlines _______________________________________________________________
010
011     Report the newlines in the indicated file.
012
013     >>> tmp_path = getfixture('tmp_path')
014     >>> filename = tmp_path / 'out.txt'
015     >>> _ = filename.write_text('foo\nbar\n', newline='')
UNEXPECTED EXCEPTION: TypeError("write_text() got an unexpected keyword argument 'newline'")
Traceback (most recent call last):
  File "/usr/lib64/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest text.show-newlines.report_newlines[2]>", line 1, in <module>
TypeError: write_text() got an unexpected keyword argument 'newline'
/home/tkloczko/rpmbuild/BUILD/jaraco.text-3.9.0/jaraco/text/show-newlines.py:15: UnexpectedException
========================================================================= short test summary info ==========================================================================
FAILED jaraco/text/__init__.py::text.read_newlines
FAILED jaraco/text/show-newlines.py::text.show-newlines.report_newlines
======================================================================= 2 failed, 24 passed in 0.11s =======================================================================
```

**Comment by bnavigator** [comment]
The newline parameter was only added in Python 3.10

https://docs.python.org/3/library/pathlib.html#pathlib.Path.write_text


@jaraco your CI jobs labeled "3.7" actually run pytest with Python 3.10:
https://github.com/jaraco/jaraco.text/runs/7820967297?check_suite_focus=true#step:5:14

**Comment by jaraco** [comment]
> CI jobs labeled "3.7" actually run pytest with Python 3.10

I don't think it's my fault:
![image](https://user-images.githubusercontent.com/308610/185484069-b3b79790-37b3-4cd9-9a37-e2bc6afe9564.png)

**Comment by jaraco** [comment]
It's a [known bug](https://github.com/actions/setup-python/issues/416) apparently fixed with v4.

**Comment by nieder** [comment]
Testing jaraco.text-4.0.0, which is supposed to work with python3.8, those two newline tests fail:
```
platform darwin -- Python 3.8.20, pytest-7.4.4, pluggy-1.4.0 -- /opt/sw/bin/python3.8
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/opt/sw/build.build/jaraco.text-py38-4.0.0-1/jaraco_text-4.0.0/.hypothesis/examples')
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /opt/sw/build.build/jaraco.text-py38-4.0.0-1/jaraco_text-4.0.0
configfile: pytest.ini
plugins: cov-6.0.0, hypothesis-6.42.1, flaky-3.8.1, timeout-2.3.1, benchmark-3.4.1, trio-0.8.0, xprocess-1.0.2, xdist-3.5.0, typeguard-0.0.0, mock-3.12.0
collected 28 items / 2 deselected / 26 selected                                                                                                                
...
_____________________________________________________ [doctest] jaraco.text.show-newlines.report_newlines ______________________________________________________
009 
010     Report the newlines in the indicated file.
011 
012     >>> tmp_path = getfixture('tmp_path')
013     >>> filename = tmp_path / 'out.txt'
014     >>> _ = filename.write_text('foo\nbar\n', newline='', encoding='utf-8')
UNEXPECTED EXCEPTION: TypeError("write_text() got an unexpected keyword argument 'newline'")
Traceback (most recent call last):
  File "/opt/sw/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest jaraco.text.show-newlines.report_newlines[2]>", line 1, in <module>
TypeError: write_text() got an unexpected keyword argument 'newline'
/opt/sw/build.build/jaraco.text-py38-4.0.0-1/jaraco_text-4.0.0/jaraco/text/show-newlines.py:14: UnexpectedException
_____________________________________________________________ [doctest] jaraco.text.read_newlines ______________________________________________________________
618 
619     >>> tmp_path = getfixture('tmp_path')
620     >>> filename = tmp_path / 'out.txt'
621     >>> _ = filename.write_text('foo\n', newline='', encoding='utf-8')
UNEXPECTED EXCEPTION: TypeError("write_text() got an unexpected keyword argument 'newline'")
Traceback (most recent call last):
  File "/opt/sw/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest jaraco.text.read_newlines[2]>", line 1, in <module>
TypeError: write_text() got an unexpected keyword argument 'newline'
/opt/sw/build.build/jaraco.text-py38-4.0.0-1/jaraco_text-4.0.0/jaraco/text/__init__.py:621: UnexpectedException
```
python3.8.20 fails.
python3.10.19 had no problems.

Easy enough to skip those tests on py38, but seems like a versioning bug at least.
pathlib2 is at 2.3.6
